"""Pydantic data schemas for request, response, health, structured agent outputs, and business profile."""

from app.schemas.health import HealthResponse, ReadinessResponse, ProviderInfo
from app.schemas.agent import (
    AgentRunRequest,
    AgentRunResponse,
    TokenUsage,
    LeadTriageResult,
)
from app.schemas.errors import ErrorResponse
from app.schemas.profile import (
    BusinessIdentity,
    AgentPersona,
    TechnicalCapabilities,
    ServiceOffering,
    IdealCustomerProfile,
    TargetBusinessCharacteristics,
    GeographicScope,
    VerticalScope,
    QualificationPreferences,
    ExclusionRules,
    OutreachConstraints,
    CampaignScope,
    LeadPulseProfile,
)
from app.schemas.search import (
    SearchQuery,
    SearchStrategy,
    CampaignLimits,
    ToolExecutionBlocked,
    SearchScopeValidationError,
    validate_search_strategy_scope,
    enforce_search_strategy_scope,
    filter_search_strategy_to_scope,
)
from app.schemas.evidence import (
    Evidence,
    LeadTriageResult as SpecialistLeadTriageResult,
    WebsiteAnalysisResult,
    AdsAnalysisResult,
    MapsAnalysisResult,
    SpecialistResearchAggregate,
)
from app.schemas.opportunity import (
    APPROVED_SERVICES,
    SERVICE_ALIAS_MAP,
    normalize_service_name,
    OpportunityResult,
)
from app.schemas.lead_analysis import (
    PriorityLevel,
    ResearchStatus,
    LeadAnalysis,
)
from app.schemas.outreach import (
    ApprovalStatus,
    DraftStatus,
    OutreachDraft,
    OutreachValidationResult,
    OutreachRecord,
    OutreachDraftRequest,
    OutreachEditRequest,
    OutreachApproveRequest,
    OutreachRejectRequest,
)
from app.schemas.persistence import (
    ResearchRunStatus,
    LeadResearchStatus,
    LeadResearchPriority,
    LeadOutreachStatus,
    ResearchRunCreate,
    ResearchRunRecord,
    LeadPersistenceRecord,
    SpecialistReportSection,
    LeadReportMetadata,
    LeadReportResponse,
    LeadListResponse,
    ResearchRunListResponse,
)

__all__ = [
    "HealthResponse",
    "ReadinessResponse",
    "ProviderInfo",
    "AgentRunRequest",
    "AgentRunResponse",
    "TokenUsage",
    "LeadTriageResult",
    "ErrorResponse",
    "BusinessIdentity",
    "AgentPersona",
    "TechnicalCapabilities",
    "ServiceOffering",
    "IdealCustomerProfile",
    "TargetBusinessCharacteristics",
    "GeographicScope",
    "VerticalScope",
    "QualificationPreferences",
    "ExclusionRules",
    "OutreachConstraints",
    "CampaignScope",
    "LeadPulseProfile",
    "SearchQuery",
    "SearchStrategy",
    "CampaignLimits",
    "ToolExecutionBlocked",
    "SearchScopeValidationError",
    "validate_search_strategy_scope",
    "enforce_search_strategy_scope",
    "filter_search_strategy_to_scope",
    "Evidence",
    "SpecialistLeadTriageResult",
    "WebsiteAnalysisResult",
    "AdsAnalysisResult",
    "MapsAnalysisResult",
    "SpecialistResearchAggregate",
    "APPROVED_SERVICES",
    "SERVICE_ALIAS_MAP",
    "normalize_service_name",
    "OpportunityResult",
    "PriorityLevel",
    "ResearchStatus",
    "LeadAnalysis",
    "ApprovalStatus",
    "DraftStatus",
    "OutreachDraft",
    "OutreachValidationResult",
    "OutreachRecord",
    "OutreachDraftRequest",
    "OutreachEditRequest",
    "OutreachApproveRequest",
    "OutreachRejectRequest",
    "ResearchRunStatus",
    "LeadResearchStatus",
    "LeadResearchPriority",
    "LeadOutreachStatus",
    "ResearchRunCreate",
    "ResearchRunRecord",
    "LeadPersistenceRecord",
    "SpecialistReportSection",
    "LeadReportMetadata",
    "LeadReportResponse",
    "LeadListResponse",
    "ResearchRunListResponse",
]
